---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint
  - repo: local
    hooks:
      - id: gen-index
        name: generate index/anchors
        entry: node scripts/gen_index_and_anchors.mjs
        language: system
        files: ^scripts/domain_list\.json$|^docs/|^schemas/
        pass_filenames: false
