---
# TRACES - Traceability Records for Aerospace Certification Evidence System
version: "1.0.0"
schema_version: "traces-v1"
timestamp: "2025-01-14T12:00:00Z"

# Traceability framework configuration
traces:
  id: "TRACES-ROOT-Q100-CONF0000"
  description: "Traceability Records for Aerospace Certification Evidence System"
  scope: "Complete CAX framework across 15 domains"
  
# Traceability types
traceability_types:
  artifact_to_requirement:
    enabled: true
    direction: "bidirectional"
    validation: "automated"
    
  domain_to_domain:
    enabled: true
    cross_references: true
    alias_support: true
    
  cax_to_cax:
    enabled: true
    pillar_integration: true
    workflow_chaining: true
    
  ata_to_system:
    enabled: true
    sns_mapping: true
    compliance_tracking: true
    
  lifecycle_to_evidence:
    enabled: true
    cadet_integration: true
    circular_tracking: true

# Evidence linkage patterns
linkage_patterns:
  det_to_det:
    pattern: "DET:<CAX>:<DOMAIN>:<SNS>:<activity>:<version>"
    hash_chain: true
    signature_verification: true
    
  requirement_to_artifact:
    pattern: "REQ-<DOMAIN>-<SNS>-<ID> → <ARTIFACT_ID>"
    validation_method: "cryptographic"
    
  domain_crossref:
    pattern: "ALIAS:<OWNER_DOMAIN>:<CO_DOMAIN>:<REF>"
    canonical_path: true
    
  ata_compliance:
    pattern: "ATA-<SNS> → <DOMAIN>:<CAX>:<EVIDENCE>"
    certification_ready: true

# Cross-domain reference mapping
cross_domain_matrix:
  AAA: ["MMM", "EEE", "OOO"]
  AAP: ["IIF", "LIB", "EDI"] 
  CCC: ["EDI", "IIS", "AAA"]
  CQH: ["PPP", "EER", "DDD"]
  DDD: ["EDI", "IIS", "OOO"]
  EDI: ["LCC", "IIS", "OOO"]
  EEE: ["EER", "LIB", "AAA"]
  EER: ["PPP", "CQH", "EDI"]
  IIF: ["LIB", "AAP", "MMM"]
  IIS: ["EDI", "OOO", "LCC"]
  LCC: ["EDI", "IIS", "OOO"]
  LIB: ["IIF", "EEE", "AAP"]
  MMM: ["AAA", "IIF", "PPP"]
  OOO: ["IIS", "EDI", "LCC"]
  PPP: ["CQH", "EER", "MMM"]

# ATA SNS compliance mapping
ata_compliance_map:
  structural_systems:
    ata_range: ["51", "52", "53", "54", "55", "56", "57"]
    primary_domain: "AAA"
    co_domains: ["MMM", "EEE"]
    
  propulsion_systems:
    ata_range: ["70", "71", "72", "73", "74", "75", "76", "77", "78", "79", "80", "81", "82", "83", "84", "85"]
    primary_domain: "PPP"
    co_domains: ["CQH", "EER"]
    
  avionics_systems:
    ata_range: ["22", "23", "31", "34", "42", "46"]
    primary_domain: "EDI"
    co_domains: ["LCC", "IIS", "OOO"]
    
  power_systems:
    ata_range: ["24", "26", "60", "61"]
    primary_domain: "EER"
    co_domains: ["EDI", "CQH"]
    
  environmental_systems:
    ata_range: ["20", "30", "36", "98"]
    primary_domain: "EEE"
    co_domains: ["EER", "AAA"]

# Validation rules
validation:
  mandatory_traces:
    - "requirement_to_design"
    - "design_to_analysis"
    - "analysis_to_verification"
    - "verification_to_validation"
    
  chain_integrity:
    hash_verification: true
    signature_validation: true
    timestamp_monotonic: true
    
  cross_domain_consistency:
    alias_validation: true
    canonical_verification: true
    circular_reference_detection: true

# Evidence chain requirements
evidence_chains:
  minimum_chain_length: 3
  maximum_gap_hours: 24
  signature_algorithms: ["Ed25519", "Dilithium2"]
  hash_algorithms: ["SHA-256", "Keccak-256"]
  
# Circular assurance integration
cadet_integration:
  enabled: true
  kpi_tracking: true
  sustainability_metrics: true
  lifecycle_closure: true
  
  circularity_traces:
    reuse_tracking: true
    waste_reduction: true
    energy_efficiency: true
    lifecycle_extension: true

# Compliance frameworks
compliance_frameworks:
  s1000d:
    enabled: true
    dmc_generation: "downstream"
    location: "CAS-SUSTAINMENT/**/S1000D/"
    
  do178c:
    enabled: true
    dal_mapping: true
    verification_traces: true
    
  do254:
    enabled: true
    hardware_traces: true
    verification_coverage: true
    
  iso14001:
    enabled: true
    environmental_traces: true
    sustainability_reporting: true

# Metadata
meta:
  owner: "TRACES-Registry-Admin"
  reviewer: "Chief-Systems-Engineer"
  last_updated: "2025-01-14T12:00:00Z"
  change_ref: "INIT-TRACES-FRAMEWORK-V1"