---
domain:
  code: CQH
  name: CRYOGENICS_QUANTUM_INTERFACES_HYDROGEN_CELLS
  description: Cryogenic systems, quantum interfaces, and hydrogen fuel cells
  version: 1.0.0
cax_integration:
  pillar: CAE-ENGINEERING
  flow: CA-DEOPTIMISE
  configuration: H2-BWB-Q100-CONF0000
ata_coverage:
  primary_codes:
  - '28'
  - '29'
  - '75'
  - '79'
  compliance_frameworks:
  - ATA iSpec 2200
  - S1000D
  - DO-178C
  - DO-254
traceability:
  cross_domain_refs:
  - PPP
  - EER
  - DDD
  traces_enabled: true
  bidirectional: true
evidence:
  det_pattern: DET:CAE:CQH:<SNS>:<activity>:V<rev>
  cadet_tracking: true
  hash_algorithm: SHA-256
  signature_algorithm: Ed25519
