---
domain:
  code: LCC
  name: LINKS_COMMUNICATIONS_CONTROL_IoT
  description: Communication links, control systems, and IoT integration
  version: 1.0.0
cax_integration:
  pillar: CAO-ORGANIZATION
  flow: CA-DEOPTIMISE
  configuration: H2-BWB-Q100-CONF0000
ata_coverage:
  primary_codes:
  - '23'
  - '31'
  - '34'
  - '42'
  - '46'
  compliance_frameworks:
  - ATA iSpec 2200
  - S1000D
  - DO-178C
  - DO-254
traceability:
  cross_domain_refs:
  - EDI
  - IIS
  - OOO
  traces_enabled: true
  bidirectional: true
evidence:
  det_pattern: DET:CAO:LCC:<SNS>:<activity>:V<rev>
  cadet_tracking: true
  hash_algorithm: SHA-256
  signature_algorithm: Ed25519
