mindmap
  root((QAL Taxonomía Extendida))
    TFA(TFA · Top Figure Aircraft)
    SI(SI · System Integration)
    CV(CV · Component Vendor)
    SE(SE · Station Envelop)
    DI(DI · Domain Interface)
    CE(CE · Component Equipped)
    CC(CC · Component Cell)
    CI(CI · Component Item)
    CP(CP · Component Part)
    FE(FE · Fundamental Element)
    QS(QS · Quantum State)
