---
domain:
  code: EER
  name: ENERGY_AND_RENEWABLE
  description: Energy systems and renewable power generation
  version: 1.0.0
cax_integration:
  pillar: CAS-SUSTAINMENT
  flow: CA-DEOPTIMISE
  configuration: H2-BWB-Q100-CONF0000
ata_coverage:
  primary_codes:
  - '24'
  - '26'
  - '60'
  - '61'
  compliance_frameworks:
  - ATA iSpec 2200
  - S1000D
  - DO-178C
  - DO-254
traceability:
  cross_domain_refs:
  - PPP
  - CQH
  - EDI
  traces_enabled: true
  bidirectional: true
evidence:
  det_pattern: DET:CAS:EER:<SNS>:<activity>:V<rev>
  cadet_tracking: true
  hash_algorithm: SHA-256
  signature_algorithm: Ed25519
