---
name: CI

on:
  push:
    branches:
      - main
      - 'release/**'
  pull_request:
    branches:
      - main

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            echo "requirements.txt not found; skipping dependency installation."
          fi

      - name: List files in workspace
        run: ls -la

      - name: Lint YAML files (optional)
        uses: ibiqlik/action-yamllint@v3
        with:
          config_file: .yamllint.yml
        continue-on-error: false  # Fail the job if lint errors are found

      - name: Validate DET packets and trace files
        run: python validate_det_traces.py

      - name: Run tests (if tests are present)
        run: |
          if [ -f pytest.ini ] || [ -d tests ]; then
            pytest
          else
            echo "No tests directory or pytest.ini found; skipping tests."
          fi
